export const PRICING = {
  PRODUCT_A_RATE: 0.025,
  PRODUCT_B_RATE: 0.01,
  PRODUCT_C_FLAT: 50,
  FULL_TERM_LOADING: 0.15,
  MIN_PRODUCT_A: 250,
  ANNUAL_DISCOUNT: 0.1,
  MULTI_CHILD_DISCOUNT: 0.1,
  MIN_ANNUAL_FEE: 5000,
  MAX_ANNUAL_FEE: 60000,
  QUOTE_VALIDITY_DAYS: 14,
  WAITING_PERIOD_DAYS: 30,
  COOLING_OFF_DAYS: 14,
} as const;

export const CURRENCY = {
  code: "AUD",
  symbol: "$",
  locale: "en-AU",
} as const;
